# Themes for repixel
# One theme per line:   name = color, color, color, ...
# Colors are hex (with or without '#'), listed DARKEST -> LIGHTEST.

mono       = 000000, 555555, AAAAAA, FFFFFF
grayscale  = 000000, FFFFFF
dithernaut = 171F41, 2F7077, FB6C76, FEEDE3
dithernaut-alt = 171F41, 2F7077, FEC09A, FEEDE3
toffee = 0d181e, 447897, d3a281, ebf7ff
chocolate-mint = 1E1310, 9A6053, 71BCCC, FEF2EE
gameboy = 0f380f 306230 8bac0f 9bbc0f
gameboy-pocket = 181818 4A513A 8C916E C5C9A6

# From lospec
# Credits, in the order below:
# Polyducks; Space Sandwich; Kirokaze;
# Kerrie Lake (x3); iLKke; GrafxKid; Javier Guerrero;
# Luis Miguel Maldonado; rsvp asap; Inkpendude.

1bit-monitor-glow = 222323, F0F6F0
2bit-demichrome   = 211E20, 555568, A0A08B, E9EFEC
kirokaze-gameboy  = 332C50, 46878F, 94E344, E2F3E4
ice-cream-gb      = 7C3F58, EB6B6F, F9A875, FFF6D3
mist-gb           = 2D1B00, 1E606E, 5AB9A8, C4F0C2
rustic-gb         = 2C2137, 764462, A96868, EDB4A1
hollow            = 0F0F1B, 565A75, C6B7BE, FAFBF6
oil-6             = 272744, 494D7E, 8B6D9C, C69FA5, F2D3AB, FBF5EF
nyx8              = 08141E, 0F2A3F, 20394F, 4E495F, 816271, 997577, C3A38A, F6D6BD
slso8             = 0D2B45, 203C56, 544E68, 8D697A, D08159, FFAA5E, FFD4A3, FFECD6
ammo-8            = 040C06, 112318, 1E3A29, 305D42, 4D8061, 89A257, BEDC7F, EEFFCC
citrink           = 201533, 252446, 254D70, 166E7A, 52C33F, B2D942, FCF660, FFFFFF
